//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicios_Jue.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEVOlucion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DEVOlucion()
        {
            this.DEtalleDEvolucions = new HashSet<DEtalleDEvolucion>();
        }
    
        public int Codigo { get; set; }
        public string Documento { get; set; }
        public int NumeroFactura { get; set; }
        public System.DateTime Fecha { get; set; }
        public int CodigoEmpleado { get; set; }
    
        public virtual CLIEnte CLIEnte { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEtalleDEvolucion> DEtalleDEvolucions { get; set; }
        public virtual EMpleadoCArgo EMpleadoCArgo { get; set; }
    }
}
