//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicios_Jue.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOtaCRedito
    {
        public int Numero { get; set; }
        public int CodigoDevolucion { get; set; }
        public int Valor { get; set; }
        public System.DateTime FechaValidez { get; set; }
    }
}
